name: Build WiX Web site

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tags:
        manual: true

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOCUSAURUS_SSR_CONCURRENCY: 5

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Npm restore
        shell: cmd
        run: ./src/restore.cmd

      - name: Build wixweb
        shell: cmd
        run: ./src/build.cmd release ${{ secrets.GITHUB_TOKEN }}

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wixweb
          path: ./build/